name: flutter_chat_ui
description: >
  Actively maintained, community-driven chat UI implementation with an
  optional Firebase BaaS.
version: 1.1.3
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^2.0.0+1
  equatable: ^2.0.3
  flutter_chat_types: 
    git: https://github.com/Jip1912/flutter_chat_types.git
  #flutter_link_previewer: ^2.1.0
  intl: ^0.17.0
  meta: ^1.7.0
  photo_view: ^0.12.0
  flutter_svg: ^0.22.0
  #flutter_link_previewer: ^2.6.0
  mollie:
    git: https://github.com/Jip1912/fluttermollie.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  assets:
    - packages/flutter_chat_ui/assets/save-money.svg
    - packages/flutter_chat_ui/assets/icon-attachment.png
    - packages/flutter_chat_ui/assets/icon-delivered.png
    - packages/flutter_chat_ui/assets/icon-document.png
    - packages/flutter_chat_ui/assets/icon-error.png
    - packages/flutter_chat_ui/assets/icon-seen.png
    - packages/flutter_chat_ui/assets/icon-send.png
    - packages/flutter_chat_ui/assets/2.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/2.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/2.0x/icon-document.png
    - packages/flutter_chat_ui/assets/2.0x/icon-error.png
    - packages/flutter_chat_ui/assets/2.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/2.0x/icon-send.png
    - packages/flutter_chat_ui/assets/3.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/3.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/3.0x/icon-document.png
    - packages/flutter_chat_ui/assets/3.0x/icon-error.png
    - packages/flutter_chat_ui/assets/3.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/3.0x/icon-send.png
